sources:
  - name: mainnet
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/dc9b1200d80a1c064c90462b9c04f264/subgraphs/id/AwyZBdna4vTAHiqBWsrQ5ErFRMi6HCgGEkQMgNBseWTL
    transforms:
      - prefix:
          value: mainnet_
          includeRootOperations: true
          includeTypes: false
  - name: arbitrum
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/dc9b1200d80a1c064c90462b9c04f264/subgraphs/id/DjUVVVSuKcCCTZSVzVXLioSd7AdqwGEyBrY4Ru5tuqzX
    transforms:
      - prefix:
          value: arbitrum_
          includeRootOperations: true
          includeTypes: false

documents:
  - "./queries/**/*.graphql"

additionalTypeDefs: |
  enum CHAIN {
    ARBITRUM
    MAINNET
  }

  extend type Subgraph {
    deployedChain: CHAIN
  }

  extend type Query {
    crossSubgraphs(skip: Int = 0, first: Int, orderBy: Subgraph_orderBy, orderDirection: OrderDirection, where: Subgraph_filter, block: Block_height): [Subgraph!]!
  }

additionalResolvers:
  - ./utils/graphclient/resolvers.ts
